language: node_js
node_js:
  - 14.6.0
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_script: 
  - npm run coverage